# Site settings
title: Adina E. Pusok - I'm building my Earth model
description: A blog and platform about Solid Earth numerical simulations
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adina E. Pusok
user_description: I am a postdoctoral researcher in Geophysics/Geodynamics at the Department of Earth Sciences, University of Oxford, and I use 2-D and 3-D, single- and two-phase numerical models to study dynamics of plate boundaries (subduction, continental collision and mid-ocean ridges).
user_title: Postdoctoral Researcher<br>Department of Earth Sciences<br>University of Oxford
email: adina.pusok@earth.ox.ac.uk
twitter_username: AdinaPusok
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
